TYPE=VIEW
query=select \'Orgao\' AS `Categoria`,`sagrafulldb`.`taborgaos`.`CodOrgao` AS `CodigoRequisicao`,`sagrafulldb`.`taborgaos`.`NomeOrgao` AS `Solicitante`,`sagrafulldb`.`taborgaos`.`NomeOrgao` AS `Titular`,`sagrafulldb`.`taborgaos`.`SiglaOrgao` AS `Sigla`,`sagrafulldb`.`taborgaos`.`NroSala` AS `Gabinete`,`sagrafulldb`.`taborgaos`.`CodOrgao` AS `CodUsuario`,`sagrafulldb`.`taborgaos`.`Andar` AS `Andar`,`sagrafulldb`.`taborgaos`.`Anexo` AS `Local`,`sagrafulldb`.`taborgaos`.`Ramal` AS `Ramal` from `sagrafulldb`.`taborgaos` union all select \'Mesa\' AS `Categoria`,`sagrafulldb`.`tabmesa`.`CodMesa` AS `CodigoRequisicao`,`sagrafulldb`.`tabmesa`.`NomeMesa` AS `Solicitante`,`sagrafulldb`.`tabmesa`.`TitularMesa` AS `Titular`,\'\' AS `Sigla`,`sagrafulldb`.`tabmesa`.`NroSala` AS `Gabinete`,`sagrafulldb`.`tabmesa`.`CodMesa` AS `CodUsuario`,`sagrafulldb`.`tabmesa`.`Andar` AS `Andar`,`sagrafulldb`.`tabmesa`.`Anexo` AS `Local`,`sagrafulldb`.`tabmesa`.`Ramal` AS `Ramal` from `sagrafulldb`.`tabmesa` union all select \'Deputado\' AS `Categoria`,`sagrafulldb`.`tabdeputados`.`CodDep` AS `CodigoRequisicao`,`sagrafulldb`.`tabdeputados`.`NomeDep` AS `Solicitante`,`sagrafulldb`.`tabdeputados`.`NomeDep` AS `Titular`,\'\' AS `Sigla`,`sagrafulldb`.`tabdeputados`.`NroGab` AS `Gabinete`,`sagrafulldb`.`tabdeputados`.`CodDep` AS `CodUsuario`,`sagrafulldb`.`tabdeputados`.`Andar` AS `Andar`,`sagrafulldb`.`tabdeputados`.`Anexo` AS `Local`,`sagrafulldb`.`tabdeputados`.`Ramal` AS `Ramal` from `sagrafulldb`.`tabdeputados`
md5=2549a077bc963127a5a8a4f9729f49e9
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001765225951545968
create-version=2
source=/* --- PARTE 1: ÓRGÃOS --- */\nSELECT \n    \'Orgao\' AS Categoria,\n    CodOrgao AS CodigoRequisicao,\n    NomeOrgao AS Solicitante,\n    NomeOrgao AS Titular,\n    SiglaOrgao AS Sigla,\n    NroSala AS Gabinete,\n    CodOrgao AS CodUsuario,\n    Andar AS Andar,\n    Anexo AS Local,\n    Ramal AS Ramal\nFROM tabOrgaos\n\nUNION ALL\n\n/* --- PARTE 2: MESA --- */\nSELECT \n    \'Mesa\' AS Categoria,\n    CodMesa AS CodigoRequisicao,\n    NomeMesa AS Solicitante,\n    TitularMesa AS Titular,\n    \'\' AS Sigla,\n    NroSala AS Gabinete,\n    CodMesa AS CodUsuario,\n    Andar AS Andar,\n    Anexo AS Local,\n    Ramal AS Ramal\nFROM tabMesa\n\nUNION ALL\n\n/* --- PARTE 3: DEPUTADOS --- */\nSELECT \n    \'Deputado\' AS Categoria,\n    CodDep AS CodigoRequisicao,\n    NomeDep AS Solicitante,\n    NomeDep AS Titular,\n    \'\' AS Sigla,\n    NroGab AS Gabinete,\n    CodDep AS CodUsuario,\n    Andar AS Andar,\n    Anexo AS Local,\n    Ramal AS Ramal\nFROM tabDeputados
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select \'Orgao\' AS `Categoria`,`sagrafulldb`.`taborgaos`.`CodOrgao` AS `CodigoRequisicao`,`sagrafulldb`.`taborgaos`.`NomeOrgao` AS `Solicitante`,`sagrafulldb`.`taborgaos`.`NomeOrgao` AS `Titular`,`sagrafulldb`.`taborgaos`.`SiglaOrgao` AS `Sigla`,`sagrafulldb`.`taborgaos`.`NroSala` AS `Gabinete`,`sagrafulldb`.`taborgaos`.`CodOrgao` AS `CodUsuario`,`sagrafulldb`.`taborgaos`.`Andar` AS `Andar`,`sagrafulldb`.`taborgaos`.`Anexo` AS `Local`,`sagrafulldb`.`taborgaos`.`Ramal` AS `Ramal` from `sagrafulldb`.`taborgaos` union all select \'Mesa\' AS `Categoria`,`sagrafulldb`.`tabmesa`.`CodMesa` AS `CodigoRequisicao`,`sagrafulldb`.`tabmesa`.`NomeMesa` AS `Solicitante`,`sagrafulldb`.`tabmesa`.`TitularMesa` AS `Titular`,\'\' AS `Sigla`,`sagrafulldb`.`tabmesa`.`NroSala` AS `Gabinete`,`sagrafulldb`.`tabmesa`.`CodMesa` AS `CodUsuario`,`sagrafulldb`.`tabmesa`.`Andar` AS `Andar`,`sagrafulldb`.`tabmesa`.`Anexo` AS `Local`,`sagrafulldb`.`tabmesa`.`Ramal` AS `Ramal` from `sagrafulldb`.`tabmesa` union all select \'Deputado\' AS `Categoria`,`sagrafulldb`.`tabdeputados`.`CodDep` AS `CodigoRequisicao`,`sagrafulldb`.`tabdeputados`.`NomeDep` AS `Solicitante`,`sagrafulldb`.`tabdeputados`.`NomeDep` AS `Titular`,\'\' AS `Sigla`,`sagrafulldb`.`tabdeputados`.`NroGab` AS `Gabinete`,`sagrafulldb`.`tabdeputados`.`CodDep` AS `CodUsuario`,`sagrafulldb`.`tabdeputados`.`Andar` AS `Andar`,`sagrafulldb`.`tabdeputados`.`Anexo` AS `Local`,`sagrafulldb`.`tabdeputados`.`Ramal` AS `Ramal` from `sagrafulldb`.`tabdeputados`
mariadb-version=100432
